# Generated by ChatGPT on 2026-03-08

from django.db import migrations, models


TIMESCALE_SQL = """
DO $$
DECLARE
    pk_name text;
    pk_includes_time boolean;
BEGIN
    BEGIN
        CREATE EXTENSION IF NOT EXISTS timescaledb;
    EXCEPTION
        WHEN undefined_file OR insufficient_privilege THEN
            RAISE NOTICE 'TimescaleDB extension is unavailable or not permitted; skipping hypertable setup.';
            RETURN;
    END;

    SELECT c.conname,
           EXISTS (
               SELECT 1
               FROM unnest(c.conkey) AS k(attnum)
               JOIN pg_attribute a
                 ON a.attrelid = c.conrelid
                AND a.attnum = k.attnum
              WHERE a.attname = 'created_at'
           )
      INTO pk_name, pk_includes_time
      FROM pg_constraint c
     WHERE c.conrelid = 'telemetry_sensorreading'::regclass
       AND c.contype = 'p'
     LIMIT 1;

    IF pk_name IS NOT NULL AND NOT pk_includes_time THEN
        EXECUTE format('ALTER TABLE telemetry_sensorreading DROP CONSTRAINT %I', pk_name);
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint c
         WHERE c.conrelid = 'telemetry_sensorreading'::regclass
           AND c.contype = 'p'
           AND EXISTS (
               SELECT 1
                 FROM unnest(c.conkey) AS k(attnum)
                 JOIN pg_attribute a
                   ON a.attrelid = c.conrelid
                  AND a.attnum = k.attnum
                WHERE a.attname = 'created_at'
           )
    ) THEN
        ALTER TABLE telemetry_sensorreading
            ADD CONSTRAINT telemetry_sensorreading_pkey PRIMARY KEY (id, created_at);
    END IF;

    PERFORM create_hypertable(
        'telemetry_sensorreading',
        'created_at',
        if_not_exists => TRUE,
        migrate_data => TRUE
    );

    CREATE INDEX IF NOT EXISTS idx_sensorreading_created_at_desc
        ON telemetry_sensorreading (created_at DESC);

    CREATE INDEX IF NOT EXISTS idx_sensorreading_device_time
        ON telemetry_sensorreading (device_id, created_at DESC);
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensorreading",
            name="device_id",
            field=models.TextField(),
        ),
        migrations.RunSQL(
            sql=TIMESCALE_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
